title: Awesome Invariant and Equivariant Filtering
author: GTSAM community
logo: null

repository:
  url: https://github.com/borglab/AwesomeEqF
  path_to_docs: .
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: false
  baseurl: https://borglab.github.io/AwesomeEqF/

execute:
  execute_notebooks: auto
  timeout: 120

sphinx:
  config:
    myst_enable_extensions:
      - amsmath
      - colon_fence
      - deflist
      - dollarmath
      - html_image
    html_theme_options:
      default_mode: light
      show_nav_level: 3
      collapse_navigation: false
